### ISSUE TITLE
fhempy-tuya - no readings updates & aiotinytuya missing

### ISSUE THREAD

**Issue by rallyeaon** [fhempy/fhempy#449]
Hi Dominik, I've experienced some troubles with fhempy-tuya. Maybe you can help:

As I do not receive Readings-Updates for them-tuya_cloud (most likely an issue of Tuya) the status wether my device is on or of is unknown and the "on" resp "off" commands are sent continuously which makes the devise "beep" extremely frequently.

I tried to switch to Tuya_local, however, having defined the device I experience the problem described below:

`Module failed to load: tuya
Maybe you need to update fhempy on this or remote peer.

Stacktrace:
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 336, in handle_function
    module_object = await self.import_module(hash)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 573, in import_module
    module_object = await utils.run_blocking(
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 72, in run_blocking
    return await asyncio.get_event_loop().run_in_executor(pool, function)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 8, in <module>
    import aiotinytuya as tt
ModuleNotFoundError: No module named 'aiotinytuya'`

It appears to me there is something ('aiotinytuya') missing in either the them_tuya or fhem container.

Any thoughts?

NB: I've described the issuee in FHEM-Forum too [https://forum.fhem.de/index.php?topic=127441.msg1317232#msg1317232](url)

Thank you

regs

Rallye

**Comment by fhempy** [comment]
Hi,

please try to install the library manually
´´´
sudo -u fhem bash
source /opt/fhem/.fhempy/fhempy_venv/bin/activate
pip install git+https://github.com/fhempy/aiotinytuya#aiotinytuya==1.12.3
´´´

**Comment by rallyeaon** [comment]
Thank you for your quick reply. Unfortunately I wasn't able to apply your suggestions successfully.
I'm running FHEM & FHEMpy (plus Fhempy_tuya-cloud, FHEMpy-fusionsolar, FHEMpy-gogleweather) in a docker-environment. To apply the suggested installation by adding
```typescript
        RUN <<EOF
          cpm install --show-build-log-on-failure --configure-timeout=360 --workers=$(nproc) --local-lib-contained /usr/src/app/3rdparty/  Protocol::WebSocket
          sudo -u fhem bash
          source /opt/fhem/.fhempy/fhempy_venv/bin/activate
          pip install git+https://github.com/fhempy/aiotinytuya#aiotinytuya==1.12.3
        EOF
``` 
to my compose-yaml did not work for me (compose doesn't accept and fails); Protocol::WebSocket is necessary since I've moved to Bookworm.

Maybe your suggestion was meant in a different way to be applied?

Thank you very much

Rallye

**Comment by fhempy** [comment]
Protocol::WebSocket is part of bookworm and can be installed with
´´´
sudo apt install libprotocol-websocket-perl
´´´

Can you provide the error message of the pip command?

**Comment by rallyeaon** [comment]
Thank you! Maybe I wasn't precise enough: I'm runningplain bookworm on a RasPi5. On top of it in a docker compose environment all applications like Portainer, FHEM, FHEMpy-fusionsolar, etc.). To get FHEM-py-fusionsolar running I need to install along with FHEM in docker Websocket protocol (Sidey is aware of it and promised to have a look @ the issue).
So my compose.yaml looks like this;
```
`services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    restart: unless-stopped
#
  fhem:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/fhem/fhem-docker:latest
        RUN <<EOF
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get update
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends nano
          LC_ALL=C apt-get autoremove -qqy && LC_ALL=C apt-get clean
          cpm install --show-build-log-on-failure --configure-timeout=360 --workers=$(nproc) --local-lib-contained /usr/src/app/3rdparty/  Protocol::WebSocket
         EOF
    restart: always
    volumes:
      - /opt/fhem/:/opt/fhem/
    container_name: fhem
    environment:
      FHEM_UID: 999
      FHEM_GID: 20
      TZ: Europe/Vienna
    networks:
      fhem_net:
        ipv4_address: 172.16.57.2
    ports:
      - "8083:8083"
      - "1883:1883"
      - "8883:8883"
      - "8084:8084"
      - "8080:8080"             # for remote ConBee II
  fhempy-fusionsolar:
    image: ghcr.io/fhem/fhempy-docker_fusionsolar:1.4.4
    container_name: FHEMpy-fusionsolar
    hostname: fhempy-fusionsolar
    restart: always
    networks:
      fhem_net:
        ipv4_address: 172.16.57.4
  fhempy-tuya_cloud:
    image: ghcr.io/fhem/fhempy-docker_tuya_cloud:1.4.4
    container_name: FHEMpy-tuya_cloud
    hostname: fhempy-tuya_cloud
    restart: always
    networks:
      fhem_net:
#
  fhempy-tuya:
    image: ghcr.io/fhem/fhempy-docker_tuya:1.4.4
    container_name: FHEMpy-tuya
    hostname: fhempy-tuya
    restart: always
    networks:
      fhem_net:
networks:
  fhem_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.57.0/24
          gateway: 172.16.57.1
#
volumes:
  portainer_data:
    name: portainer_data
    external: true`
```
I see no way to install "aiotinytuya" as described in your 1st reply as ID FHEM exists in the container environment only. Further, installation of websocket-protocol on the bare system was not leading to success, I had to install within docker-environment.
Maybe there is a way I'm not aware of!?

Thank you

Rallye
